[platform]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    coryjfowler/MCP_CAN_lib @ ^1.5.0

[env:native]
platform = native
build_flags = -D NATIVE_TEST
